### PR TITLE
Updated Qt to 5.12.8

### PR DESCRIPTION
**Pull request by sergey-chernikov**
Mainly a polish release of Qt (e.g. removed useless output in Linux console).
Tested the build on Ubuntu 20.04

### CODE REVIEW

**Comment by Ation** [comment]
Need to check build on OSX

**Comment by sergey-chernikov** [comment]
BTW, build was also tested on Windows

**Comment by Ation** [comment]
Build is fine on OSX

**Comment by sergey-chernikov** [comment]
Anything that prevents it from merging atm?

**Pull request merged**
